[versions]

# Core build tools
agp = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.4"
dagger = "2.59"

compose-bom = "2026.01.01"
retrofitVersion = "2.11.0"
roomVersion = "2.8.4"
timberVersion = "5.0.1"
junitVersion = "4.13.2"
appcompat = "1.7.0"

composeNavigation = "2.7.7"
composeActivity = "1.10.1"
composeCoil = "2.7.0"
okhttpLoggingInterceptor = "4.12.0"
hiltAndroidx = "1.2.0"
datastorePreferences = "1.1.7"
workKtx = "2.9.0"
androidxTestExt = "1.1.5"
androidxTestEspresso = "3.5.1"
mockWebserver = "4.11.0"
navigationTesting = "2.7.7"
kotlinxCollectionsImmutable = "0.3.7"
spotless = "6.25.0"
composeLintChecks = "1.3.1"
circuit = "0.33.0"
kotlinxSerializationJson = "1.10.0"
kotlinxSerializationConvertor = "1.0.0"


[libraries]
tools-buildGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-pluginGradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }


compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "composeCoil" }
compose-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLoggingInterceptor" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinxSerializationConvertor" }



hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltAndroidx" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltAndroidx" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltAndroidx" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }
work = { module = "androidx.work:work-runtime-ktx", version.ref = "workKtx" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "composeLintChecks" }




junit = { module = "junit:junit", version.ref = "junitVersion" }
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
mock-webserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockWebserver" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationTesting" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
robolectric = "org.robolectric:robolectric:4.14.1"
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "circuit" }
circuit-android = { module = "com.slack.circuit:circuitx-android", version.ref = "circuit" }
circuit-codegen-annotations = { module = "com.slack.circuit:circuit-codegen-annotations", version.ref = "circuit" }
circuit-gesturenav = { module = "com.slack.circuit:circuitx-gesture-navigation", version.ref = "circuit" }
circuit-overlay = { module = "com.slack.circuit:circuit-overlay", version.ref = "circuit" }
circuit-codegen = { module = "com.slack.circuit:circuit-codegen", version.ref = "circuit" }
kotlinx-atomicfu = "org.jetbrains.kotlinx:atomicfu:0.25.0"


[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = "com.diffplug.spotless:6.25.0"
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
