name: Android Build

on: pull_request

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_MOHSEN_ID }}
                  token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  format: markdown
                  message: 'Hi sir build branch *[${{ github.head_ref }}]* get started! ðŸš€'

            - uses: actions/checkout@v3

            - name: Share checkout complete on Telegram
              env:
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
                  TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_GROUP_TOPIC_ID }}
                  MESSAGE: '*[${{ github.head_ref }}]* checkout branch complete! ðŸŒŸâœ¨âœ…ðŸš€'
              run: |
                  curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_GROUP_ID} -d message_thread_id=${TELEGRAM_TOPIC_ID} -d text="${MESSAGE}"

            - name: Set Up JDK
              uses: actions/setup-java@v3
              with:
                distribution: 'zulu'
                java-version: 17

            - name: Change wrapper permissions
              run: chmod +x ./gradlew

            - name: Spotless Check
              continue-on-error: false
              run: ./gradlew spotlessCheck --no-configuration-cache

            - name: Run Tests
              continue-on-error: false
              run: ./gradlew testDebugUnitTest

            - name: Share unit test Success on Telegram
              if: ${{ success() }}
              env:
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
                  TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_GROUP_TOPIC_ID }}
                  MESSAGE: '*[${{ github.head_ref }}]* unit tests SUCCESS âœ…ðŸŽ‰ðŸ”¬ðŸ‘'
              run: |
                  curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_GROUP_ID} -d message_thread_id=${TELEGRAM_TOPIC_ID} -d text="${MESSAGE}"

            - name: Share unit test failure on Telegram
              if: ${{ failure() }}
              env:
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
                  TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_GROUP_TOPIC_ID }}
                  MESSAGE: '*[${{ github.head_ref }}]* unit tests FAILED ðŸ˜²âŒ Check for details! ðŸ•µï¸â€â™‚ï¸ðŸ“Š'
              run: |
                  curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_GROUP_ID} -d message_thread_id=${TELEGRAM_TOPIC_ID} -d text="${MESSAGE}"


            - name: Build Project
              run: ./gradlew assemble


            - name: Share Apk on Telegram
              if: ${{ success() }}
              env:
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
                  TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_GROUP_TOPIC_ID }}
                  MESSAGE: '*[${{ github.head_ref }}]* Debug APK Build in Progress! ðŸ—ï¸ðŸ“±â¬‡ï¸ðŸš€ðŸ“Ž Keep an Eye'
              run: |
                APK_PATH=$(find ${{ github.workspace }}/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
                if [ -f "$APK_PATH" ]; then
                curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
                -F chat_id="${TELEGRAM_GROUP_ID}" \
                -F message_thread_id="${TELEGRAM_TOPIC_ID}" \
                -F document=@"${APK_PATH}" \
                -F caption="${MESSAGE}"
                else
                echo "APK file not found."
                exit 1
                fi

            - name: Share app build failure on Telegram
              if: ${{ failure() }}
              env:
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
                  TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_GROUP_TOPIC_ID }}
                  MESSAGE: '*[${{ github.head_ref }}]* App build FAILED on branch ðŸ˜²âŒ Check logs for details! ðŸ“‘ðŸ”'
              run: |
                  curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_GROUP_ID} -d message_thread_id=${TELEGRAM_TOPIC_ID} -d text="${MESSAGE}"

#    Add Telegram Secret Key to Your Repository
#    1. Go to your GitHub repository.
#    2. Click on Settings (top-right).
#    3. In the left sidebar, click Secrets and variables > Actions.
#    4. Click New repository secret.
#    5. Enter a name (e.g., MY_SECRET_KEY).
#    6. Enter your secret value.
#    7. Click Add secret.

